blank_issues_enabled: true
contact_links:
  - name: Lavalink Discord
    url: https://discord.gg/ZW4s47Ppw4
    about: Please ask and answer questions here or in discussions
  - name: Lavalink Discussions
    url: https://github.com/lavalink-devs/Lavalink/discussions/categories/q-a
    about: Please ask and answer questions here or in Discord
